image: debian/stable
packages:
  - clang
  - dash
  - gcc
  - tcc
sources:
  - https://git.sr.ht/~ashn/autil
tasks:
  - test-clang-debug: |
      cd autil
      make clean test CC=clang CFLAGS='$(GNU_DBG) $(SANITIZE)'
  - test-clang-release: |
      cd autil
      make clean test CC=clang CFLAGS='$(GNU_REL)'
  - test-gcc-debug: |
      cd autil
      make clean test CC=gcc CFLAGS='$(GNU_DBG) $(SANITIZE)'
  - test-gcc-release: |
      cd autil
      make clean test CC=gcc CFLAGS='$(GNU_REL)'
  - test-tcc: |
      cd autil
      make clean test CC=tcc
triggers:
  - action: email
    condition: failure
    to: "<me@ashn.dev>"
